build:
  image: registry.inetu.org/centos:6
  stage: build
  script:
    - yum -y install gcc openssl-devel
    - ./configure --disable-ssl --enable-command-args --enable-bash-command-substitution
    - make
    - make clean
    - ./configure --enable-ssl --enable-command-args --enable-bash-command-substitution
    - make
